name: CI/CD pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE: ${{ secrets.CI_REGISTRY }}rhmt-front:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to harbor registry
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.beecrouse.uz -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -f Dockerfile -t ${{ env.IMAGE }} .

      - name : Push Docker image to Harbor
        run: docker push ${{ env.IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            docker pull ${{ env.IMAGE }}
            docker stop rhmt-front || true
            docker rm rhmt-front || true
            docker run -d --restart=always -p 8083:8080 --name rhmt-front ${{ env.IMAGE }}
